// make this an object with countries corresponding to country codes
const countries = 
[
    'Argentina',
    'Australia', 
    'Austria', 
    'Belgium', 
    'Brazil', 
    'Bulgaria', 
    'Canada', 
    'China', 
    'Colombia', 
    'Cuba',
    'Cyprus', 
    'Czech Republic', 
    'Egypt', 
    'France', 
    'Germany',
    'Greece', 
    'Hong Kong', 
    'Hungary', 
    'India', 
    'Indonesia', 
    'Ireland', 
    'Israel', 
    'Italy', 
    'Japan', 
    'Korea, South', 
    'Latvia', 
    'Lithuania', 
    'Malaysia', 
    'Mexico', 
    'Morocco', 
    'Netherlands', 
    'New Zealand', 
    'Nigeria', 
    'Norway', 
    'Philippines', 
    'Poland', 
    'Portugal', 
    'Romania', 
    'Russia', 
    'Saudi Arabia', 
    'Serbia',
    'Singapore', 
    'Slovakia', 
    'Slovenia', 
    'South Africa', 
    'Sweden', 
    'Switzerland', 
    'Taiwan', 
    'Thailand', 
    'Turkey',
    'United Arab Emirates', 
    'Ukraine', 
    'USA', 
    'Venezuela',
];

export default countries;